spring.application.name=cannia

# ===============================
# BASE DE DATOS RENDER POSTGRESQL
# ===============================

spring.datasource.url=jdbc:postgresql://dpg-d75dah7diees73bs4uk0-a.oregon-postgres.render.com:5432/cannia
spring.datasource.username=cannia_user
spring.datasource.password=3qNHReLcRoSgNzAy1Em6OBQChEYfYQVx

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



#Dependencias nesesarias para el envio de correos

sendgrid.api.key=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
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587

#Se utiliza para la recuperacion de contraseñas
spring.mail.username=cannia.scrum2@gmail.com
spring.mail.password=tdyp wjuv sdlw bxlo

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Dependencias para el wed service(Pasarela de pagos)
stripe.api.key=sk_test_51SYKWZCjwJYz7HpJKzOWlAU9rgBp457N4myuyAnnn4haZ5Buh6ymGykzSHljC4c4NLIb8XNGWUWjqzUDB89h7tHD00sxJgS3Sl

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}

server.forward-headers-strategy=framework

app.url=https://cannia.onrender.com


server.servlet.session.timeout=10m

